### ISSUE TITLE
S01E01 Epic 7: Front-end

### ISSUE THREAD

**Issue by xardass** [swarmcity/SwarmCityPM#20]
implementation
======================
- [x] Style page new-request
- [x] Style page confirm-new-request
- [x] Style page new-request-processing 
- [x] Create display-create-request
- [x] Input validation and button logic on display create-request
- [x] error & processing logic on page new-request-processing

Dependencies:
===================
Styling can proceed without dependencies

Time Estimate
=====================
8
