### ISSUE TITLE
S01E01 Epic 7: Create hashtagItem, send it to API and store hash

### ISSUE THREAD

**Issue by xardass** [swarmcity/SwarmCityPM#21]
implementation
======================

- [x] Create redux property for hashtagItem
- [x] Use UUIDv4 for hashtagItemId and sha3 for hashtagItemHash
- [x] Combine data for hashtagItem JSON
- [x] Serialize JSON to String
- [x] Send String to API 
- [x] Serialize JSON to String 
- [x] Create redux property for itemDataHash
- [x] Store API reply to itemHash

Dependencies: #20 
===================
- [x] Pages have been styled to make input possible (#20)
- [x] Function ipfsAdd exists as specified

Time Estimate
=====================
7
