### ISSUE TITLE
S01E01 Epic 18: Location-Slider

### ISSUE THREAD

**Issue by xardass** [swarmcity/SwarmCityPM#33]
implementation
======================
- [x] Style display-create-request with the slider
- [x] Check for navigator permissions
- [x] Add routing on missing permissons to /location 
- [x] Dynamic update of location setting
- [x] Get current location via data-location
- [x] Make default location world-wide via geoHash
- [x] Get corresponding geoHash when submitting request
- [x] Create itemGeoHash redux Get & Set where needed
- [x] Send itemGeoHash to IPFS on unlocking

Dependencies:
===================
All dependencies are met.

Time Estimate
=====================
5
