### ISSUE TITLE
S01E01 Epic 8: Hashtag SimpleDeal rework

### ISSUE THREAD

**Issue by xardass** [swarmcity/SwarmCityPM#36]
implementation
======================
- [x] Create display-hashtag-simpledeal
- [x] Copy page-hashtag over to new file with new logic
- [x] Write mock hashtag data to finish epic
- [x] Rewrite & copy old animations to new page-hashtag

Dependencies: #38 
===================
- [x] Consensus on Hashtag data format

Time Estimate
=====================
6
