### ISSUE TITLE
S01E01 Epic 8: URL to hashtag resolve

### ISSUE THREAD

**Issue by xardass** [swarmcity/SwarmCityPM#41]
implementation
======================
- [x] Create display-get-hashtag
- [x] Check for eth address in url
- [x] Request new hashtag data from socket
- [x] Handle response data on page-new-request
- [x] Add new display on new-request & hashtag and remove old logic

Dependencies: #38 
===================
- [x] Correct data format response from API

Time Estimate
=====================
7
