### ISSUE TITLE
S01E01 Epic 8: Sort and Style item involved display

### ISSUE THREAD

**Issue by xardass** [swarmcity/SwarmCityPM#42]
implementation
======================
- [x] Move display-items-involved & display-hashtag-items in new display
- [x] Write data-hashtag-simpledeal sort logic
- [x] Trigger sort functions from within displays when API populates Hashtag 	
- [x] Style item involved in case user is seeker
- [x] Default data if future epic
- [x] Use default data for missing IPFS metadata

Time Estimate
=====================
7
