### ISSUE TITLE
S01E01 Epic 8: IPFS Avatar resolver 

### ISSUE THREAD

**Issue by xardass** [swarmcity/SwarmCityPM#43]
In this task we iterate over all hashtag items and use a chain of promises to resolve all item's avatar IPFS hashes to their base64 value. If a base64 value is already present, don't send a new call.

implementation
======================

- [x] Default values on missing base64
- [x] Store & maintain resolved values in local storage
- [x] Recursively resolve item's avatars
- [x] Dynamically polymer update array properties 

Time Estimate
=====================
8
