### ISSUE TITLE
S01E01 Epic 8: Styling hashtag & items

### ISSUE THREAD

**Issue by xardass** [swarmcity/SwarmCityPM#44]
In this task we iterate over all hashtag items and use a chain of promises to resolve all item's avatar IPFS hashes to their base64 value. If a base64 value is already present, don't send a new call.

implementation
======================

- [x] Hashtag position fixed
- [x] Show items not involved
- [x] Format timestamp
- [x] Style divider between item displays
- [x] style new-item counter
- [x] populate new-item counter & show based on number

Time Estimate
=====================
4

**Comment by BvL13** [comment]
Please move this to "Done & Merged" when it is done and in order to get the payment.
Thank you.
