### ISSUE TITLE
S01E02 Epic 11: Styling hashtag & items

### ISSUE THREAD

**Issue by xardass** [swarmcity/SwarmCityPM#45]
In this task we show a mockup list of replies
======================

- [x] Structure item detail solution to allow simpledeal component
- [x] Create the new displays
- [x] Allow for different styling if user is seeker
- [x] Style the replies
- [x] Resolve the avatar with iron image over a public ipfs gateway

Time Estimate
=====================
8
