### ISSUE TITLE
S01E02 Epic 10: Item state interaction difference

### ISSUE THREAD

**Issue by xardass** [swarmcity/SwarmCityPM#46]
In this task we show options for interaction with an item depening on user's state (owner, non-owner, has replied or not)
======================

- [x] New displays for cancel & reply buttons
- [x] Fix relative display logic
- [x] Improve asynchronous element getting with async

Time Estimate
=====================
5
