### ISSUE TITLE
S01E02 Epic 10: Reply input view

### ISSUE THREAD

**Issue by xardass** [swarmcity/SwarmCityPM#47]
In this task we build the input reply view on the item detail
======================

- [x] Allow for view switching on user input
- [x] Style the reply input view
- [x] Create displays for interacting elements

Time Estimate
=====================
5
